### ISSUE TITLE
starting-blocks errors on Node 0.12.x

### ISSUE THREAD

**Issue by jonboydell** [LeanMeanFightingMachine/slush-starting-blocks#3]
When running the gulp command to get the starting-blocks site running I get an error (below).  Google seems to think that this might be something to do with using execSync on Node 0.12.x, ever seen it before?

mcsb-11685:test-starting-blocks jon.boydell$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/jon.boydell/Projects/test-starting-blocks/node_modules/execSync/index.js:30:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/jon.boydell/Projects/test-starting-blocks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/jon.boydell/Projects/test-starting-blocks/tasks/dploy.coffee:8:12)
  at Object.<anonymous> (/Users/jon.boydell/Projects/test-starting-blocks/tasks/dploy.coffee:1:1)

**Comment by stuartkeith** [comment]
Happened to see this in the feed.

Node 0.12 has its own execSync built in, so the execSync in package.json has been abandoned and won't work.

I fixed it in Havana here: https://github.com/LeanMeanFightingMachine/Havana-Mojito/blob/11f10d07ba33c04ac0b102b04cfc50c0d5d2d98e/tasks/module.coffee
